name: matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        node_version: [16, 18]
    runs-on: ubuntu-latest
    steps:
     - name: Log
       run: node -v
     - uses: actions/checkout@v3
       with:
         node-version: ${{matrix.node_version}}
         run: node -v