name: Shell commands

on: [push]

jobs:
  run-shell-commands: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello, world!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platfrom.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Directory powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash